version: "3.5"

services:
  flytnow-video-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/workspace/src
    command: npm start
    container_name: flytnow-video-app
    ports:
      - "4200:4200"
    # restart: always
